### ISSUE TITLE
Board Display not working!!

### ISSUE THREAD

**Issue by KUHELI96** [TrustworthyComputing/csaw_esc_2019#10]
This is to inform you that we are facing an issue with the ESC 19 board that is provided. On connecting the provided setup to the USB port of the computer, the display isn't working. Furthermore, on trying to install the avrLoader.sh provided, we get the following errors:

Teensy Loader, Command Line, Version 2.1
Read "ArduinoISP.ino.hex": 13004 bytes, 5.0% usage
Found HalfKay Bootloader
Programming.............
Booting

avrdude: Version 6.3
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "/etc/avrdude.conf"
         User configuration file is "/home/esc/.avrduderc"
         User configuration file does not exist or is not a regular file, skipping

         Using Port                    : /dev/ttyACM0
         Using Programmer              : arduino
         Overriding Baud Rate          : 19200
         AVR Part                      : ATmega1284
         Chip Erase delay              : 55000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    10   128    0 no       4096    8      0  9000  9000 0xff 0xff
           flash         65    10   256    0 yes    131072  256    512  4500  4500 0xff 0xff
           lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00

         Programmer Type : Arduino
         Description     : Arduino
         Hardware Version: 2
         Firmware Version: 1.18
         Topcard         : Unknown
         Vtarget         : 0.0 V
         Varef           : 0.0 V
         Oscillator      : Off
         SCK period      : 0.1 us

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.01s

avrdude: Device signature = 0x000000
avrdude: Yikes!  Invalid device signature.
         Double check connections and try again, or use -F to override
         this check.
![Problem_CSAW_ESC](https://user-images.githubusercontent.com/57289207/68070746-43735900-fd98-11e9-8819-951b7abac0d9.jpg)

Please let us know, what can be done. 

Regards,
SEAL_IITKGP, 
ESC Finalist, India

**Comment by grant-h** [comment]
Not the organizers, but I had some cold solder joints that prevented me from scanning the RFID. I had to resolder them to get it to work again. From your error logs, it looks like there could be a connection issue.

The atmega1284 is programmed via serial ISP: pins PB5, PB6, PB7 ([manual](http://ww1.microchip.com/downloads/en/DeviceDoc/ATmega164A_PA-324A_PA-644A_PA-1284_P_Data-Sheet-40002070A.pdf) page 310). These are hooked up to the teensy via pins 13 (DOUT), 14 (DIN), and 20 (LED_SCK) ([schematic](https://github.com/TrustworthyComputing/csaw_esc_2019/blob/master/ESC19BoardSchematic.pdf)). Maybe try wiggling these pins or reflowing them?

**Comment by ptrick9** [comment]
This appears to be a burned AVR rather than a communiations issue. We preprogrammed all of the boards such that the display would be working and LEDs flashing when plugged in. Unless the communications issue occured at the exact moment that the AVR was reset via the programmer (unlikely) the screen and onboard LEDs would still function. 

If any other teams have similar issues, please contact your local challenge leads for better troubleshooting. 

This issue has recently been resolved via private emails so I'm going to close it.
