### ISSUE TITLE
Multiple possible solutions

### ISSUE THREAD

**Issue by buecheko** [TrustworthyComputing/csaw_esc_2019#8]
Hi ESC Team,
we have encountered a challenge where we found multiple solutions for p which solve the challenge with different hashes. 

What would be the proper way to report this?

Albsociety

**Comment by ptrick9** [comment]
As previously stated, we are not able to comment on any challenge specifics. If teams believe that there are more than one solution to a challenge they may report those in the report. Teams must specify one solution that works as their answer to the challenge. This is the only solution that will be tested when determining how many points the team will receive from solved challenges (correctness portion as described here:https://github.com/TrustworthyComputing/csaw_esc_2019/blob/master/challenge_description.md) . If teams feel that they have found additional solutions, they may detail these, and/or how they found them in the report. These extra solutions etc. will be considered in the  performance and efficiency category.
