### ISSUE TITLE
Presentation and Video

### ISSUE THREAD

**Issue by chq-matteo** [TrustworthyComputing/csaw_esc_2019#9]
Hello, is it possible to clarify some points about the deliverables?

1. Are the video and presentation due the 1st of November or they can be submitted at a later date?
2. What should be the content of the video?
    Should it be a demo of a solution?
    Can we include footage of us while we were working on the challenges?
3. What should be the content of the presentation?
   Since we only have 8 slides, can we present only one or two challenges that we found more interesting to showcase?

Thank you

**Comment by ptrick9** [comment]
1. The due dates have been updated and are [here](https://github.com/TrustworthyComputing/csaw_esc_2019/blob/master/Deliverables.md)

2. The content of the video should highlight your approach, novel solutions, etc. 

3. The presentation should also highlight your approaches and novel solutions. You may of course include whatever you desire in the presentation.
